### ISSUE TITLE
Position::XYZH2TrackPos() fails in a roundabout

### ISSUE THREAD

**Issue by brifsttar** [esmini/esmini#56]
Hi Emil,

First of all, congratulations on the 2.0 release! Great milestone for this amazing project.

I'm still (ab)using MoveAlongS to move along sidewalks on my OpenDRIVE network. I recently found an issue in `Position::XYZH2TrackPos()`, which fails to position on the correct road. Here's a failing coordinate: 

```(X=-33.29556885,Y=161.15220703)```

It's on road 146, and there's a whole section of that road where the method insists on putting me on road 2764, which is the entrance road just above on the following capture (selected area in blue in the problematic section in 146)

![image](https://user-images.githubusercontent.com/53508707/100538563-c7fd0900-3230-11eb-9c90-556416887ba7.png)

Here's a gif on my test setup in Unreal Engine. I'm manually moving an object along the sidewalk, and the track coordinates are displayed on the right-side panel. I've added a marker in the world to indicate where road 146 is starting. As you can see, for quite a long stretch, the method says I'm still on road 2764, at maximum S; however it seldom correctly places me on road 146.

![test](https://user-images.githubusercontent.com/53508707/100538631-2cb86380-3231-11eb-9eb3-314a5a9231e9.gif)

Since `Position::XYZH2TrackPos()` got rewritten to use OSI points, I'm a bit lost in it, so I didn't try to find the explanation for this issue. If you don't have time to look at it, I'll try to find the root cause.

**Comment by brifsttar** [comment]
Still testing, I have pretty much the exact same issue at the following coordinate:

```(X=-69.06877441,Y=135.39619141)```

![image](https://user-images.githubusercontent.com/53508707/100544903-42418380-3259-11eb-85c9-eb4d9229c46a.png)

We're supposed to be on road 36, but we're placed on road 945 (the turning road just above it).

**Comment by eknabevcc** [comment]
Yes, I see the problem. Thanks a lot for reporting the issue along with illustrated excellent description! We will look into it - certainly we want this to work for non driving lanes as well.

**Comment by brifsttar** [comment]
I just had a quick look, but I think the method computes the `closestPointDist` using the road center as reference (https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L4499), which in my case would definitely cause an issue:

![image](https://user-images.githubusercontent.com/53508707/100758995-6be0e300-33f0-11eb-98ce-0a618b19af20.png)

If I'm right, I'm not quite sure what the best solution would be.

**Comment by eknabevcc** [comment]
It's with a mix of frustration and stimulation I attack your issues. For every bug we hunt down and eliminate, there is always another one around the corner :) 
But the motivation is to improve esmini one baby-step at a time. So I'm very grateful for these reports. Actually your road network provides great variety and challenges helping us to improve the RoadManager. 

Anyway: We found a few issues that hopefully have been fixed with commit 6f32277. Hopefully solving both the "road 146" issue and the "closestPointDist" issue, at least part of the problem. Please test and let me know the result.

**Comment by brifsttar** [comment]
I know the feeling! But quite frankly, you've done an amazing job at squashing those bugs. We currently have a wide variety of scenarios in this network, involving both cars and pedestrians on most roads, so it's a pretty great achievement to be able to handle all of those.

Back to the issue, it's fixed for road 36/945, but only partially fixed for 146/2764. As can be seen below, the mismatch is reduced to ~70cm.

![road](https://user-images.githubusercontent.com/53508707/101609603-70685580-3a07-11eb-84ba-46cfc27bb8e1.gif)

Here's a mismatch coordinate if you want to have a closer look at it.

```
(X=-34.07105469,Y=163.84646484)
```

On a side note, the other day I was wondering if it'd be a good idea to have some sort of regression testing on this network, something like this:

```
buggy_xyz_pos = (X=-69.06877441,Y=135.39619141)
roadmanager::Position pos(buggy_xyz_pos)
assert(pos.road_id == 36)
```

That way, we'd make sure each new fix in roadmanager didn't break any previous fix. If you're interested, I can check internally if we can publicly release our network, and maybe make a PR with all the issues I previously reported added as test cases.

**Comment by esmini** [comment]
Definitely a good idea putting tests like this in the suite of regression tests. We have integrated a unit test framework and an initial set of tests for local execution. We have plans for extending test suite and attaching to CI. So at that point (within coming weeks) I think we could add a test like this - let's start with one as a POC. 
An idea would be to have a brutal subset of you road network. Like only the two or three roads involved in the tricky location. A few subsets like that would 1, be quicker to load and execute, 2. perhaps easier to get approval for sharing?
Anyway, let's get back to the test discussion in some weeks. We need to do other stuff first.

Then, regarding the remaining, but probably not the last one 🙂, issue. It's a bit hard for me to verify (I don't have that fancy interactive way of moving position - perhaps we'll implement something similar at some point), but I implemented one small improvement (commit 2c43593) for cases in between/close to endpoints of roads. Would be interesting to hear if it have any effect on your side.

**Comment by brifsttar** [comment]
Thank you for the patch :-)

The mismatch gap has been reduced from ~70cm to ~30cm. I also tested on a driving lane to make sure there wasn't an issue specific with sidewalks, and I have same gap size. Here's a mismatch coordinate on a driving lane:

```(X=-30.03613770,Y=165.07068359,Z=0.000000)```

I'll leave it up to you whether you want to dig in deeper to get a better match, or if you want to leave it at that and maybe come back to it latter. I'll probably investigate the issue myself this weekend, I want to try to contribute a bit more than just bug reports, and I also want to get a better understanding of `Position::XYZH2TrackPos()`.

And on a side note, I'm still hoping to open-source my whole UE4 toolset, but it's too early for us. However that gizmo is trivial to implement, it's just a basic UE4 actor feeding its world position to RoadManager, which then does all the work :-)

**Comment by brifsttar** [comment]
Just a few notes from my (ongoing) investigation.

https://github.com/esmini/esmini/blob/ea220a6c20bf73c61192e468497263de2d3c2a6d/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L4532

In my case, `osiPoints->GetNumOfOSIPoints()` is 13, with OSI points for each S, except 12 (we jump froml 11 to end, which is 13)

![image](https://user-images.githubusercontent.com/53508707/101980021-7312b700-3c62-11eb-8208-2f1ce609474e.png)

I'm not sure if that's working as intended? I have pretty much zero knowledge with regards to OSI points, so I'm really just asking.

Anyway, just after that bit of code, we have

https://github.com/esmini/esmini/blob/ea220a6c20bf73c61192e468497263de2d3c2a6d/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L4550

But can this condition ever be `true`? The for loop condition is `k < osiPoints->GetNumOfOSIPoints()-1` (note the strictly inferior), so `k == osiPoints->GetNumOfOSIPoints() - 1` can never be `true`, right?

**Comment by brifsttar** [comment]
Also, a few notes on `inside`

https://github.com/esmini/esmini/blob/ea220a6c20bf73c61192e468497263de2d3c2a6d/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L4537

First of all, `inside` is not set to `true` when evaluating road 146, which seems weird to me. One of the reason could be this:

https://github.com/esmini/esmini/blob/ea220a6c20bf73c61192e468497263de2d3c2a6d/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L4569-L4574

There is a check for the "triangle area" between OSI points, but not at road extremities. Consider the following, with the blue line being the first OSI vector (i.e. first two points), then you have the yellow triangle that will be considered as "outside" even though it's not.

![image](https://user-images.githubusercontent.com/53508707/101980512-321ca180-3c66-11eb-9dc9-ab2b54c19884.png)

Also, I'm having trouble understanding what this `inside` value ends up being used for. I would have assumed that it would lower the weight, or give some kind of "bonus" to the road, but the only mention I find is

https://github.com/esmini/esmini/blob/ea220a6c20bf73c61192e468497263de2d3c2a6d/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L4599-L4602

Which I don't really understand. `z` is used just after, but since it's `fabs`'d, it can't be used as "weight lowering". And in my case, even with `inside` as false, the following line always added 0 to `distTmp`.

https://github.com/esmini/esmini/blob/ea220a6c20bf73c61192e468497263de2d3c2a6d/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L4610

So if my analysis is correct, one of the issue would be with `inside` not being properly computed for road extremities. Maybe I'll try to patch it later today to see if I'm correct.

**Comment by eknabevcc** [comment]
Huge thanks for testing and pushing this further. I'll try to summarize my findings:

**1. Drive lane mismatch X=-30.03613770,Y=165.07068359,Z=0.000000**
This point lies in the "triangle" between two roads, just as you state and illustrate in your image.
I think it lies in the area A in my image below:

![areas](https://user-images.githubusercontent.com/29146839/101989894-a7f32e00-3ca3-11eb-998f-cf0197b5ee0f.png)

If you test this point: x="-30.01" y="164.95", you'll see that it snaps to 146 even though it still not "inside".
This is because it's now in the area B, i.e. neither inside 2765 or 146, but now closer to 146.

The root cause for this issue (gaps in between roads) is that the OSI lines, which is made up from OSI points, doesn't start at exact correct angle/heading. As in you picture, the blue line heading is not in the tangent of the curve. The shorter line segments would be, the less wrong heading... 

Clearly both area A and B belongs to road 146, but the approximation of curves with OSI lines introduces this gap issue...

Maybe we can find a way to identify this areas as "inside" and then get a better match of s-value and everything. We have information that the road (146) is directly connected to the current one (2765). So maybe its possible... but I don't get any splendid idea right now :)

**2. Missing OSI point** 
There is an OSI requirement regarding how big the deviation/error from actual road may be. So for a straight line there can be fewer OSI points, or in other words longer distance between them.
In this very case I think there is a straight line in the end of the road segment, which explains a gap in OSI points. So it should be OK.

Would be great to nail this gap-thing. Will probably think more about it tomorrow :)

**Comment by brifsttar** [comment]
> Maybe we can find a way to identify this areas as "inside" and then get a better match of s-value and everything

Couldn't we add two checks: one for before first and one for after last OSI points? We have the real heading from the geom, and the approximate heading from the OSI vector. There's probably some math magic that can tell us if the point is within the "triangle" formed by the heading difference. I can probably write it up if needed.

**Comment by brifsttar** [comment]
Some random ideas with regards to "before first" check (our current buggy case)

1) Simply repeat

https://github.com/esmini/esmini/blob/ea220a6c20bf73c61192e468497263de2d3c2a6d/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L4568-L4569

But for "first OSI segment". Since we don't have a "previous" segment to compare it with (i.e. `sLocalTmp`), we could use the previous section's last OSI segment.

However, since both segments are approximation of real geometry, we could still have mismatch I think. This method would allow us to determine if a point currently falls in the "mismatch" area, but it wouldn't tell us with certainty which road it belongs to.

2) The same idea, but instead of taking the previous section's last segment, we build a brand new vector, tangent to the geometry at s=0.

![image](https://user-images.githubusercontent.com/53508707/102007343-86885580-3d28-11eb-9119-4336985273ea.png)

If the point projects on the new vector but not on the OSI one, then it's `inside` (I think). One question would be the length of the new vector. If it's too long, it could cause issues. It should probably be strictly inferior to the length of the first OSI segment, maybe even half or less?

**Comment by eknabevcc** [comment]
Very good ideas! 👍 I tried along your ideas to implement (commit 5bb69ef) a check for road endpoints (both ends). 
The approach is simple:
1. Create normal vectors for 1. the actual heading and 2. the OSI line
2. Create a vector from object position to the road end point 
3. Calculate cross products for pairs (actual normal X object_pos_vector) and (object_pos_vector X OSI normal)
They correspond to the two angles "a" and "b" in image below.
If sign if the two cross products are the same, the point is within this triangular area - i.e. "inside".

![image](https://user-images.githubusercontent.com/29146839/102009079-5b583300-3d35-11eb-88e7-7cf22fbfccbb.png)

Please try and see if it works better - and if we introduced some bad side effects...

**Comment by brifsttar** [comment]
Thanks for the commit!

However, it doesn't seem to work. Now, at the same mismatch coordinate as before(X=-30.03613770,Y=165.07068359,Z=0.000000), the mismatch isn't even with 2765, but with 705! Which isn't that close (but it seems to have a rather... interesting geometry).

![image](https://user-images.githubusercontent.com/53508707/102009603-c5bea280-3d38-11eb-8100-957cf044a251.png)

![road](https://user-images.githubusercontent.com/53508707/102009604-cb1bed00-3d38-11eb-947f-8aaec4ff6ff5.gif)

Also, as you may see in the gif, there's some back and forth between the roads matching when sliding the point. It's not as clear cut as before. I didn't have a chance to look at your code just yet, I only ran this test. If I find the time, I'll look for the issue in the afternoon.

**Comment by brifsttar** [comment]
The geometry of road 705 by the way:

![image](https://user-images.githubusercontent.com/53508707/102009967-4a122500-3d3b-11eb-90c8-fba85a744070.png)

**Comment by brifsttar** [comment]
https://github.com/esmini/esmini/blob/5bb69efd1d467cfda5e89149b04492f1af7a88f6/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L4607

https://github.com/esmini/esmini/blob/5bb69efd1d467cfda5e89149b04492f1af7a88f6/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L4617

The vector is normalized, therefore `GetLengthOfLine2D` returns 1. I'll dig deeper after lunch :-)

**Comment by eknabevcc** [comment]
Yes, I see a few issues - side effects. I'll try to look into it while watching F1 :)

**Comment by eknabevcc** [comment]
Good finding. I fixed that distance/normalize issue, plus a few  others (commit a6a56bf). E.g. make sure normals pointing to the same side as object position.  
I think we make small progress, step by step. Sometimes 2 forward and 1 backwards - but forward nonetheless!

**Comment by brifsttar** [comment]
Thanks for your reactivity! Look at that perfect road transition :-)

![road](https://user-images.githubusercontent.com/53508707/102013747-52c22580-3d52-11eb-8639-c8b15904ee82.gif)

I've moved the gizmo around to see if anything weird occurred, but nothing to report. I also ran our scenario with 33 pedestrians walking along sidewalks (which initially lead me to discover this issue), and they all seemed to behave correctly, so no obvious side effects to report either.

I'll have my colleague test this with all of her scenarios next week, but I'm guessing it'll work. And if it doesn't, I'll make sure to report it ;-)

Once again, thank you so much for your amazing support, our exchanges are always a pleasure :-)

**Comment by eknabevcc** [comment]
Ah, very good news and nice video! 
Thank you for persistent support with excellent reports and ideas. This has no doubt improved RoadManager in a way not possible without your input. It has been a pleasure, this joint effort! And probably there's more issues to find, so I stay ready for further reports :)

**Comment by brifsttar** [comment]
> I'll have my colleague test this with all of her scenarios next week, but I'm guessing it'll work

Tests done, everything is working as intended :-)

**Comment by eknabevcc** [comment]
So good to hear! Thanks for info :)
