### ISSUE TITLE
Lane changes aren't possible for vehicles with assigned routes.

### ISSUE THREAD

**Issue by daydreamingwill** [esmini/esmini#74]
When a lane-change action is triggered for an entity which has already had a route assigned to it in init actions, strange behaviour occurs in which the entity seems to erratically jump between different lanes - neither completing the lane change nor properly following the route. Running the route assignment action and lane change independently works with no issues. Is this a know limitation? Thanks.

**Comment by eknabevcc** [comment]
Thanks for reporting this issue. The route concept in esmini has some limitations. E.g. it resolves a perfectly connected sequence of road and lanes. So in order to stay on this connected "path", lane changes get special treatment if entity is following a route: It will not actually change lane, just offset. Staying in original lane will ensure that connecting roads and lanes are resolved as intended by the route. 
This could of course be done in a better way, but would require a refactorization of route concept which is not currently planned in near time.
That said, the idea is to support lane change, so I would like to look into this issue to see if we can solve the bug you found. I already did some quick testing with modified ltap-od scenario. I found some issues, however not exact what you described. Anyway I created a branch and committed a few changes I would like you to test: https://github.com/esmini/esmini/tree/fix_route_lane_change
Is it possible for you to build the branch yourself? Otherwise I can post a link to an executable. In that case, what platform? Win, Linux or Mac?
And by the way, if you still see issues (which I expect), it would be great if you could share your two scenarios - the one that fails and the one that work (all in storyboard). If you don't want to share complete scenarios, perhaps you can trim to bare minimum?
Any help is appreciated.

**Comment by daydreamingwill** [comment]
Many thanks for getting back to me. A link to a Windows executable would definitely be much appreciated. As you say, I won't be able to share the entirety of the scenarios but I can certainly share two similar, trimmed down, scenarios - assuming there are still issues.

**Comment by eknabevcc** [comment]
Please test this [esmini.exe](https://www.dropbox.com/s/epd9nobbwz0v5rj/esmini.exe?dl=1).
It solves at least one issue where parallel actions could mess up the longitudinal s-coordinate along route. If there are still issues I look forward to analyze further with trimmed scenario.

**Comment by tmIdiada** [comment]
Hi eknabevcc,

I have a question regarding these lane changes and your offset. I hope you can help me.

Do I understand it correctly and the lane changes now are only possible on straight roads?
Because, if the target vehicle drives on a curve (on the circle segment or euler spiral / clothoid segment of the curve), then a lateral offset in target vehicle's local coordinate frame in combination with the longitudinal offset of the lane change curve would lead to leaving the road and not to the planned position on target lane.

Or have I misunderstood the concept of the implemented lane change?

**Comment by eknabevcc** [comment]
Lane changes should be possible on all roads with any geometry and curvature. The issue we try to solve here is when lane change is requested for a vehicle currently following a route. In that special case our current intention is to prioritize the route. Which means that it will (logically) stick to the lanes as defined by the route but adjust the offset as result from any lane change. 

Tricky to explain. In the video below (hope you can see it) there are two versions of the esmini ltap-od example scenario: In the first run the red car moves alone the route as originally specified. In the second run it makes a lane change into the left lane, going into opposite direction, then stays there. When reaching the intersection the route says turn left, which it also obeys - still keeping in "wrong" lane. I think, after all, this is the expected behavior (but all the time the logical lane-id is the right original lane). 

https://user-images.githubusercontent.com/29146839/106942061-fcef7580-6723-11eb-8c4a-e01e443cd54d.mp4

Maybe I didn't really understand your concern and perhaps this example is not representative. In that case, please explain again. I wouldn't be surprised if there are use cases that the current implementation doesn't support.

**Comment by eknabevcc** [comment]
By the way, this video shows better (using `--road_features on` argument) that the red car stays on the route in terms of logical lane belonging. So the lane change is in effect treated as a lane offset, when object is attached to a route. That's the current implementation at least, which is not "set in stone".

https://user-images.githubusercontent.com/29146839/106991446-80d24d80-6776-11eb-8af4-068220b20d8b.mp4

**Comment by tmIdiada** [comment]
Hi,
thanks a lot for the videos. I see on the default cut-in example that lane changes work also on curved roads, but I still don't really understand how the methodology works. If I'm on curved road and planning a lane change with specific lateral velocity. Then I know at starting point the dy for the lane change. But at the end point of the lane change the dy depends strongly on the original route (To know the dy, I have to know the dx or the duration, if the input is lateral velocity, then the calculation is quite hard, especially if the road data is not given by mathematical curves). Can it be, that you are calculating the lane change for straight trajectories, so that dy of end point is equal to dy at starting point of the lane change and that you do an overlapping / sum of the two trajectories to get all positions of the lane change. So, the final trajectory with included lane change is the sum of the original curved trajectory without lane change and a straight trajectory including the lane change.

It would be great, if such methodology of trajectory calculations could be explained, especially regarding the difference between sinusoidal and cubic, what are the advantages/disadvantages, is something else planned in the near future, ...? I'm working at moment for example on clothoid based trajectories for lane changes, maybe if I understand better here the methodology, that I could contribute something interesting.

**Comment by eknabevcc** [comment]
The motion in esmini (and OpenDRIVE and OpenSCENARIO) is typically (but not always) defined in terms of the road coordinate system, which basically is a longitudinal (s) and lateral (t) component following the road reference line. Here's an image from the [OpenDRIVE 1.6 User Guide](https://www.asam.net/standards/detail/opendrive/):
![image](https://user-images.githubusercontent.com/29146839/107329629-b21d8700-6ab0-11eb-82aa-11e8d0387abd.png)
The transition dynamics elements in the lateral actions, LaneOffset and LaneChange operates on the lateral dimension (t). 

Now, I think your question is: When considering lateral rate (velocity) or acceleration, should it take any road curvature into account? In esmini, the straight answer is: No. Only the t-component is considered (and remember, s/t system is following the road curvature). So a lane change will have the exact same longitudinal and lateral profile, in terms of road coordinates, regardless of road curvature.

That said, I agree that it can make sense to include road curvature to find out actual lateral acceleration in addition to any lateral motion (in terms of road coordinates) of the vehicle. Perhaps it should be optional, depending on the use case/test scope. 

I should also stress that the above is my own, and esmini, interpretation. Should not be taken as OpenSCENARIO reference.

**Comment by tmIdiada** [comment]
Now it is all clear. Thank you a lot for the explanation and yes you understood my question and concerns very well.
Tip: Your explanation in desmos for the cubic lane change curve is very confusing, because you are using the letter a for lateral velocity, I think the following picture describes it better what you are doing and which equations are finally used in the code
![image](https://user-images.githubusercontent.com/78544110/107371107-29204300-6ae4-11eb-9b89-8f4731ae3409.png)
Your description must not be so detailed like mine, but the usage of a as lateral velocity and talking about maximal lateral acceleration, when you meant maximal lateral velocity was very confusing.

**Comment by eknabevcc** [comment]
Thanks for reviewing and pointing out the confusion. Yes, it was a typical copy-paste error from jumping between velocity and acceleration. As you also observed, LaneOffset and LaneChange actions differ in (among others) that way: LaneOffset defined in terms of Maximum lateral acceleration while LaneChange can be defined in terms of lateral rate (speed). 

I have corrected the variable names and clarified based on your input👍 : [https://www.desmos.com/calculator/j9h7jzcowe](https://www.desmos.com/calculator/j9h7jzcowe). Link in code has been [updated ](https://github.com/esmini/esmini/commit/9661c91aaaa0c782b5f94d595e3f7e2e22cc7f32)as well.

**Comment by eknabevcc** [comment]
You think this is OK and we can close the issue for now?

**Comment by daydreamingwill** [comment]
> You think this is OK and we can close the issue for now?

Hi @eknabevcc sorry for my lack of response on this issue. Unfortunately, my attention was pulled in another direction not long after my initial post. I did test the binary but it didn't seem to fix the erratic lane changing behavior. That being said, after talking to colleagues, my suspicion is that the OpenDRIVE map I was using might have had some issues of its own. 

For now, closing this issue seems fair. Perhaps in the future, I'll be able to do a bit more investigation... Thanks!

**Comment by eknabevcc** [comment]
Thanks for feedback. The OpenDRIVE could be a root cause. But of course, there might an issue within esmini as well. Anyway, I agree, let's close for now - and don't hesitate to reopen later.
